FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

EXPOSE 80
EXPOSE 443

WORKDIR /
COPY ["./Api.csproj",""]
RUN dotnet restore "./Api.csproj"

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build-env /out .
ENTRYPOINT ["dotnet", "api.dll"]
